[build]
  # Path to the directory where your frontend build files are located
  publish = "frontend/dist"
  
  # Command to build your frontend (for example, if you're using React)
  command = "npm run build"

# Optional: Specify the Node.js environment version
[build.environment]
  NODE_VERSION = "16"

# Redirects (optional, if needed for handling routes)
[[redirects]]
  from = "/api/*"
  to = "https://social-media-platform-l27s.onrender.com"
  status = 200
  force = true

# For caching (optional)
[build.processing]
  bundle = false
  minify = true
